FROM golang:1.24-alpine3.21 AS build
RUN apk add build-base git
WORKDIR /src
COPY . .
RUN make build_linux

FROM alpine:3.21
RUN apk add --no-cache ca-certificates && \
    update-ca-certificates
COPY --from=build /src/_output/linux/yarr /usr/local/bin/yarr
EXPOSE 7777
ENTRYPOINT ["/usr/local/bin/yarr"]
CMD ["-addr", "0.0.0.0:7777", "-db", "/data/yarr.db"]
